name: Deploy the main branch
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    timeout-minutes: 10
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci

      - name: NG Build
        run: npm run build:ci

      - name : Deploy
        uses: lowply/deploy-firebase@v0.0.5
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: nicolas-corvi-webdev


#replace with custom code
      - name: Send whatsapp message
        env:
            account_sid: ${{ secrets.ACCOUNT_SID }}
            auth_token: ${{ secrets.AUTH_TOKEN }}
            to_whatsapp_no: ${{ secrets.TO_WHATSAPP_NUMBER }}
        run:
          curl -X POST -d "Body=New push to portfolio" -d "From=+14155238886" -d "To=${{env.to_whatsapp_no}}" "https://api.twilio.com/2010-04-01/Accounts/${{env.account_sid}}/Messages" -u "${{env.account_sid}}:${{env.auth_token}}"

